name: squad-hub
recipe: laravel

excludes:
  - vendor
  - node_modules

config:
  php: '8.4'
  via: nginx
  webroot: public
  xdebug: false

services:
  mysql:
    type: mysql:8.4
    portforward: 3306

  appserver:
    type: php:8.4
    ssl: true
    build_as_root:
      - apt-get update -y
      - apt install nano libxslt1-dev -y
      - apt-get install cron -y
      - docker-php-ext-install xsl
      - service cron start
    build:
      - '[ ! -f ".env" ] && cp .env.example .env || echo ".env already present"'
      - composer install
      - php artisan key:generate
      - php artisan migrate
    overrides:
      volumes:
        - ./:/app:cached
      depends_on:
        - database
    run_as_root:
      - service cron start
    run:
      - crontab .lando/cron.txt
